name: Publish

on:
  push:
    tags:
    - 'v*'

jobs:
  pack:
    runs-on: ubuntu-latest
    name: Build CacheService
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            9.0.x
      - name: Build
        run: dotnet build src/CacheService.csproj
      - name: Test
        run: dotnet test tests/CacheService.Tests.csproj
      - name: Create NuGet packages
        run: |
          GITHUB_VERSION="${{ github.ref }}"
          GITHUB_VERSION=(${GITHUB_VERSION##*/})
          RELEASE_VERSION="${GITHUB_VERSION//v}"
          ARRAY_VERSION=(${RELEASE_VERSION//-/ })
          VERSION="${ARRAY_VERSION[0]}"
          VERSION_SUFFIX="${ARRAY_VERSION[1]}"
          dotnet pack -c Release -o nupkg ./src/CacheService.csproj -p:AssemblyVersion=$VERSION -p:VersionPrefix=$VERSION -p:VersionSuffix=$VERSION_SUFFIX -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nupkg
          path: ./nupkg/*.*
          retention-days: 1
  nugets:
    needs: pack
    runs-on: ubuntu-latest
    name: Publish NuGet package
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: nupkg
          path: ./nupkg
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true
      - name: Publish NuGet packages
        run: |
          dotnet nuget push ./nupkg/*.nupkg -k ${{ secrets.NUGET_KEY }} -s https://api.nuget.org/v3/index.json
  release:
    needs: pack
    runs-on: ubuntu-latest
    name: Upload packages to Release
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: nupkg
          path: ./nupkg
      - name: Get Version
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      - name: Create Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Release ${{ steps.vars.outputs.tag }}
          tag_name: ${{ steps.vars.outputs.tag }}
          draft: false
          prerelease: false
          files: |
            nupkg/*.nupkg
  cleanup:
    needs: [ nugets, release ]
    runs-on: ubuntu-latest
    steps:
      - uses: geekyeggo/delete-artifact@v1
        with:
          name: |
            nupkg
